### ISSUE TITLE
Bug: build menu active during death animation

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#70]
During the player death animation you can still have the build menu open if you hold shift.

The build mode should be completely deactivated during death.

**Comment by alkaitagi** [comment]
Fixed

**Comment by perfecthumaninterface** [comment]
While the build menu visuals no longer show up, the red boundaries of existing structures still show when shift is held.

**Comment by alkaitagi** [comment]
Fixed. Now building boundaries are shown in debug mode **[~]** as well.
